package com.neovation.model;

public enum RequestStatus {
    SUBMITTED,
    UNDER_REVIEW,
    PROPOSAL_SENT,
    IN_REVIEW, CONSULTATION,
    REVISION_REQUESTED,
    PROPOSAL_APPROVED,
    PAYMENT_RECEIVED,
    IN_PROGRESS,
    COMPLETED,
    CANCELLED,
    ON_HOLD
}